title: JF S치nchez
author: Jeisson S치nchez
description: "El Marketing hace parte de mi gesti칩n profesional, me gusta ense침ar, leer libros y escribir, aprend칤 desarrollo y estad칤stica en aplicaci칩n con el lenguaje Python 游냀."
keywords: [Aleksandr Hovhannisyan, github pages resume, github pages portfolio, github pages personal website]
url: "https://jfsanchez.pw/"
github_username: 

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
include: ['_pages']

defaults:
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      isPost: false
      layout: "default"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      customJS: ["blogImage"]
      isPost: true
      layout: "post"
      permalink: /blog/:categories/:title/
  -
    scope:
      path: "_posts/dev"
    values:
      needsCodeFont: true
      categories: [Dev]
  -
    scope:
      path: "_posts/cs101"
    values:
      needsCodeFont: true
      categories: [CS101]
  -
    scope:
      path: "_posts/gaming"
    values:
      categories: [Gaming]
  -
    scope:
      path: "_posts/music"
    values:
      categories: [Music]


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
